### ISSUE TITLE
Missing "right click" step to get to Object Properties window

### ISSUE THREAD

**Issue by parasyte** [melonjs/tutorial-platformer#2]
This was brought up today on the forum: https://groups.google.com/d/msg/melonjs/Xv5yn-VuxOc/-WV4FSYLPacJ

**Comment by obiot** [comment]
So what is missing is "right click on the object to oepn the object property window" ?

Sure, but in the mean time, I would like to add as well that the idea of the tutorial is more to show how Tiled is integrated with melonJS, rather than explaining the very basic feature of Tiled itself, my point is that Tiled has its own website for that :)

**Comment by parasyte** [comment]
I really agree! But at the same time it will avoid this "problem with the tutorial" coming up again. (It is a perceived problem. Not a real one.)

**Comment by obiot** [comment]
sure I agree too :)

closing this ticket!
