### ISSUE TITLE
New screenshot for objectProperties - shows incorrect width/height

### ISSUE THREAD

**Issue by hipwelljo** [melonjs/tutorial-platformer#20]
The image that shows Object Properties for the mainPlayer (part 3) shows incorrect values for the width and height. It should be fixed (width should be 64 and height 64 - that worked for me) by providing a new screenshot.

**Comment by obiot** [comment]
just realized that the screenshots also show "spritewidth" when it should actulally show "framewidth" as we changed that in 2.1.0.

Unfortunately, I'm abroad with only a window machine and cannot do the screenshots (as all the other ones were made on OSX), so if anyone could make it that would be great, and I would then update it :P

**Comment by parasyte** [comment]
![screen shot 2015-05-25 at 2 44 05 pm](https://cloud.githubusercontent.com/assets/456942/7802519/8d6c1e8a-02ec-11e5-8d85-4222fd96d9f6.png)

Here's the screenshot requested. Looks like there are other screens that should be recaptured, since the properties UI has changed substantially in newer Tiled releases.

Here's the CoinEntity (part 5)

![screen shot 2015-05-25 at 2 47 28 pm](https://cloud.githubusercontent.com/assets/456942/7802546/0c730cde-02ed-11e5-87c2-a59298b485a3.png)

There's also a `me.LevelEntity` screenshot in part 8, but it's _missing_ from map1.tmx in the step8 and step9 source files. (This is a bug of its own) So I didn't capture that screenshot.
