### ISSUE TITLE
Incorrect depth instructions?

### ISSUE THREAD

**Issue by emarcotte** [melonjs/tutorial-platformer#29]
The tutorial suggests setting depth to Infinity using this fragment:

```
    // make sure our object is always draw first
    this.z = Infinity;
```

It should be `this.pos.z` as far as I can tell, or least if you're not using `autoDepth`. Perhaps the tutorial should just remove it altogether and mention `autoDepth` as an alternative to managing depth?

**Comment by obiot** [comment]
indeed, good catch, as this is a left-over (dead) code that slipped through the cracks  :)

by default now (since 2.x i think) , auto-depth is on by default, which means that except if a z parameter is specified through the addChild function, it will automatically set the z value. so this line has no effect even if it was corrected to use `this.pos.z`

**Comment by Dillybob92** [comment]
If anyone see's this in the future make sure to sort if `pos.z` was changed after initialization/adding. :+1:
